#!/usr/bin/env python3
"""Render captured terminal output as an SVG terminal window.

Demo assets for the blog and README are generated from real command output by piping
it through this script. That matters: a drawn or mocked-up "screenshot" of a clinical
governance tool can depict behaviour the software does not have, and nobody reading it
can tell. Anything produced here can be regenerated by re-running the command.

Usage:
    python scripts/check_guardrails.py | python scripts/render_terminal_svg.py \\
        --title "practice-loops $ python scripts/check_guardrails.py" \\
        --output docs/framework/demo-guardrail-check.svg

    python scripts/render_terminal_svg.py --input captured.txt --title "..." --output out.svg
"""
import argparse
import html
import pathlib
import sys

# Rough advance width for a 13px monospace glyph. Slightly generous so long lines do
# not clip on fonts wider than DejaVu Sans Mono.
CHAR_W = 7.3
FONT_SIZE = 13
LINE_H = 19
PAD_X = 18
PAD_Y = 14
TITLEBAR_H = 34

BG = "#12151A"
TITLEBAR = "#1C2027"
FG = "#D6DAE0"
DIM = "#7C8797"
GREEN = "#4FC08D"
RED = "#E5615A"
AMBER = "#D9A94C"
CYAN = "#5AB6C7"


def colour_for(line):
    s = line.strip()
    if s.startswith("ok "):
        return GREEN
    if s.startswith("FAIL") or s.startswith("error"):
        return RED
    if s.startswith("===") or s.startswith("---") or set(s) <= set("=-"):
        return DIM
    if s.startswith("-") and ":" in s:
        return AMBER
    if s.startswith("All ") or s.startswith("manifests OK"):
        return GREEN
    if s.startswith("🩺") or s.startswith("Total") or s.startswith("Average"):
        return CYAN
    return FG


def render(lines, title):
    # Drop trailing blank lines so the window is not mostly empty space.
    while lines and not lines[-1].strip():
        lines.pop()
    widest = max([len(title) + 6] + [len(l) for l in lines]) if lines else len(title) + 6
    width = int(widest * CHAR_W + PAD_X * 2)
    height = int(TITLEBAR_H + PAD_Y * 2 + len(lines) * LINE_H)

    out = [
        f'<svg viewBox="0 0 {width} {height}" xmlns="http://www.w3.org/2000/svg" '
        f'role="img" font-family="ui-monospace, SFMono-Regular, Menlo, Consolas, '
        f'DejaVu Sans Mono, monospace">',
        f'<title>{html.escape(title)}</title>',
        f'<desc>Terminal output captured from a real command run: '
        f'{html.escape(title)}</desc>',
        f'<rect x="0" y="0" width="{width}" height="{height}" rx="10" fill="{BG}"/>',
        f'<rect x="0" y="0" width="{width}" height="{TITLEBAR_H}" rx="10" fill="{TITLEBAR}"/>',
        f'<rect x="0" y="{TITLEBAR_H-10}" width="{width}" height="10" fill="{TITLEBAR}"/>',
        f'<circle cx="18" cy="17" r="5" fill="#E5615A"/>',
        f'<circle cx="36" cy="17" r="5" fill="#D9A94C"/>',
        f'<circle cx="54" cy="17" r="5" fill="#4FC08D"/>',
        f'<text x="72" y="22" font-size="12" fill="{DIM}">{html.escape(title)}</text>',
    ]

    y = TITLEBAR_H + PAD_Y + FONT_SIZE
    for line in lines:
        if line.strip():
            out.append(
                f'<text x="{PAD_X}" y="{y}" font-size="{FONT_SIZE}" '
                f'fill="{colour_for(line)}" xml:space="preserve">'
                f'{html.escape(line)}</text>'
            )
        y += LINE_H

    out.append("</svg>")
    return "\n".join(out) + "\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--title", required=True, help="Text shown in the title bar")
    ap.add_argument("--output", required=True, help="Path to write the .svg")
    ap.add_argument("--input", help="Read from this file instead of stdin")
    args = ap.parse_args()

    if args.input:
        text = pathlib.Path(args.input).read_text(encoding="utf-8", errors="replace")
    else:
        text = sys.stdin.read()

    lines = text.replace("\t", "    ").splitlines()
    if not lines:
        print("error: no input to render", file=sys.stderr)
        return 1

    out = pathlib.Path(args.output)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render(lines, args.title), encoding="utf-8")
    print(f"wrote {out} ({len(lines)} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
